# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'db_config_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DBConfigForm(object):
    def setupUi(self, DBConfigForm):
        DBConfigForm.setObjectName("DBConfigForm")
        DBConfigForm.resize(606, 353)
        self.gridLayout_2 = QtWidgets.QGridLayout(DBConfigForm)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.port_lineEdit = QtWidgets.QLineEdit(DBConfigForm)
        self.port_lineEdit.setObjectName("port_lineEdit")
        self.gridLayout.addWidget(self.port_lineEdit, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(DBConfigForm)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(DBConfigForm)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.token_lineEdit = QtWidgets.QLineEdit(DBConfigForm)
        self.token_lineEdit.setObjectName("token_lineEdit")
        self.gridLayout.addWidget(self.token_lineEdit, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(DBConfigForm)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.url_lineEdit = QtWidgets.QLineEdit(DBConfigForm)
        self.url_lineEdit.setObjectName("url_lineEdit")
        self.gridLayout.addWidget(self.url_lineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(DBConfigForm)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(DBConfigForm)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.name_lineEdit = QtWidgets.QLineEdit(DBConfigForm)
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.gridLayout.addWidget(self.name_lineEdit, 2, 1, 1, 1)
        self.bucket_lineEdit = QtWidgets.QLineEdit(DBConfigForm)
        self.bucket_lineEdit.setObjectName("bucket_lineEdit")
        self.gridLayout.addWidget(self.bucket_lineEdit, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(DBConfigForm)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.org_lineEdit = QtWidgets.QLineEdit(DBConfigForm)
        self.org_lineEdit.setObjectName("org_lineEdit")
        self.gridLayout.addWidget(self.org_lineEdit, 4, 1, 1, 1)
        self.save_pushButton = QtWidgets.QPushButton(DBConfigForm)
        self.save_pushButton.setObjectName("save_pushButton")
        self.gridLayout.addWidget(self.save_pushButton, 6, 1, 1, 1)
        self.cancel_pushButton = QtWidgets.QPushButton(DBConfigForm)
        self.cancel_pushButton.setObjectName("cancel_pushButton")
        self.gridLayout.addWidget(self.cancel_pushButton, 7, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(DBConfigForm)
        QtCore.QMetaObject.connectSlotsByName(DBConfigForm)

    def retranslateUi(self, DBConfigForm):
        _translate = QtCore.QCoreApplication.translate
        DBConfigForm.setWindowTitle(_translate("DBConfigForm", "DB Config"))
        self.label_3.setText(_translate("DBConfigForm", "Server NAME"))
        self.label_4.setText(_translate("DBConfigForm", "TOKEN"))
        self.label_5.setText(_translate("DBConfigForm", "ORG"))
        self.label_2.setText(_translate("DBConfigForm", "PORT"))
        self.label_6.setText(_translate("DBConfigForm", "BUCKET"))
        self.label.setText(_translate("DBConfigForm", "URL"))
        self.save_pushButton.setText(_translate("DBConfigForm", "Guardar"))
        self.cancel_pushButton.setText(_translate("DBConfigForm", "Cancelar"))
