# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ua_config_window_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UAConfigForm(object):
    def setupUi(self, UAConfigForm):
        UAConfigForm.setObjectName("UAConfigForm")
        UAConfigForm.resize(606, 353)
        self.gridLayout_2 = QtWidgets.QGridLayout(UAConfigForm)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.uri_lineEdit = QtWidgets.QLineEdit(UAConfigForm)
        self.uri_lineEdit.setObjectName("uri_lineEdit")
        self.gridLayout.addWidget(self.uri_lineEdit, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(UAConfigForm)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(UAConfigForm)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.prod_uri_lineEdit = QtWidgets.QLineEdit(UAConfigForm)
        self.prod_uri_lineEdit.setObjectName("prod_uri_lineEdit")
        self.gridLayout.addWidget(self.prod_uri_lineEdit, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(UAConfigForm)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.endpoint_lineEdit = QtWidgets.QLineEdit(UAConfigForm)
        self.endpoint_lineEdit.setObjectName("endpoint_lineEdit")
        self.gridLayout.addWidget(self.endpoint_lineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(UAConfigForm)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(UAConfigForm)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.app_uri_lineEdit = QtWidgets.QLineEdit(UAConfigForm)
        self.app_uri_lineEdit.setObjectName("app_uri_lineEdit")
        self.gridLayout.addWidget(self.app_uri_lineEdit, 2, 1, 1, 1)
        self.man_name_lineEdit = QtWidgets.QLineEdit(UAConfigForm)
        self.man_name_lineEdit.setObjectName("man_name_lineEdit")
        self.gridLayout.addWidget(self.man_name_lineEdit, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(UAConfigForm)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.name_lineEdit = QtWidgets.QLineEdit(UAConfigForm)
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.gridLayout.addWidget(self.name_lineEdit, 4, 1, 1, 1)
        self.save_pushButton = QtWidgets.QPushButton(UAConfigForm)
        self.save_pushButton.setObjectName("save_pushButton")
        self.gridLayout.addWidget(self.save_pushButton, 6, 1, 1, 1)
        self.cancel_pushButton = QtWidgets.QPushButton(UAConfigForm)
        self.cancel_pushButton.setObjectName("cancel_pushButton")
        self.gridLayout.addWidget(self.cancel_pushButton, 7, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(UAConfigForm)
        QtCore.QMetaObject.connectSlotsByName(UAConfigForm)

    def retranslateUi(self, UAConfigForm):
        _translate = QtCore.QCoreApplication.translate
        UAConfigForm.setWindowTitle(_translate("UAConfigForm", "OPC UA Config"))
        self.label_3.setText(_translate("UAConfigForm", "APP URI"))
        self.label_4.setText(_translate("UAConfigForm", "PRODUCT URI"))
        self.label_5.setText(_translate("UAConfigForm", "NAME"))
        self.label_2.setText(_translate("UAConfigForm", "URI"))
        self.label_6.setText(_translate("UAConfigForm", "MANUFACTURER NAME"))
        self.label.setText(_translate("UAConfigForm", "ENDPOINT"))
        self.save_pushButton.setText(_translate("UAConfigForm", "Guardar"))
        self.cancel_pushButton.setText(_translate("UAConfigForm", "Cancelar"))
