# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'var_modbus_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VariablesModbus(object):
    def setupUi(self, VariablesModbus):
        VariablesModbus.setObjectName("VariablesModbus")
        VariablesModbus.resize(974, 495)
        self.gridLayout = QtWidgets.QGridLayout(VariablesModbus)
        self.gridLayout.setObjectName("gridLayout")
        self.close_pushButton = QtWidgets.QPushButton(VariablesModbus)
        self.close_pushButton.setObjectName("close_pushButton")
        self.gridLayout.addWidget(self.close_pushButton, 2, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(VariablesModbus)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.equipos_listView = QtWidgets.QListView(VariablesModbus)
        self.equipos_listView.setObjectName("equipos_listView")
        self.verticalLayout.addWidget(self.equipos_listView)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_10 = QtWidgets.QLabel(VariablesModbus)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.lecturas_listView = QtWidgets.QListView(VariablesModbus)
        self.lecturas_listView.setObjectName("lecturas_listView")
        self.verticalLayout_2.addWidget(self.lecturas_listView)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 3, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_16 = QtWidgets.QLabel(VariablesModbus)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        self.var_tableWidget = QtWidgets.QTableWidget(VariablesModbus)
        self.var_tableWidget.setObjectName("var_tableWidget")
        self.var_tableWidget.setColumnCount(0)
        self.var_tableWidget.setRowCount(0)
        self.verticalLayout_3.addWidget(self.var_tableWidget)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 4, 1, 1)

        self.retranslateUi(VariablesModbus)
        QtCore.QMetaObject.connectSlotsByName(VariablesModbus)

    def retranslateUi(self, VariablesModbus):
        _translate = QtCore.QCoreApplication.translate
        VariablesModbus.setWindowTitle(_translate("VariablesModbus", "Variables Modbus"))
        self.close_pushButton.setText(_translate("VariablesModbus", "Salir"))
        self.label.setText(_translate("VariablesModbus", "Equipos:"))
        self.label_10.setText(_translate("VariablesModbus", "Lecturas"))
        self.label_16.setText(_translate("VariablesModbus", "Variables"))
